// Wel <-> Pi bridge extension. Auto-generated by Wel — do not edit by hand.
// Reports Pi's active working time to Wel's loopback AI-time endpoint. Reads the
// endpoint port + token from Wel's data dir at runtime; if Wel is not running
// (files missing) every call simply no-ops. Never throws into Pi.
import { readFileSync } from "node:fs";
import type {
  ExtensionAPI,
  ExtensionContext,
} from "@earendil-works/pi-coding-agent";

const ENDPOINT_FILE = "/Users/nejo/Library/Application Support/Wel/ai-endpoint";
const TOKEN_FILE = "/Users/nejo/Library/Application Support/Wel/ai-token";

export default function (pi: ExtensionAPI) {
  let welSession: string | null = null; // Wel session id for this Pi process, or null

  async function post(
    path: string,
    body: Record<string, string>,
  ): Promise<Record<string, unknown> | null> {
    try {
      const port = readFileSync(ENDPOINT_FILE, "utf8").trim();
      const token = readFileSync(TOKEN_FILE, "utf8").trim();
      if (!port || !token) return null;
      const res = await fetch(`http://127.0.0.1:${port}${path}`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify(body),
        signal: AbortSignal.timeout(3000),
      });
      if (!res.ok) return null;
      const data: unknown = await res.json().catch(() => ({}));
      return typeof data === "object" && data !== null && !Array.isArray(data)
        ? (data as Record<string, unknown>)
        : {};
    } catch {
      return null;
    }
  }

  function projectFrom(ctx: ExtensionContext) {
    return ctx.cwd.split("/").filter(Boolean).pop() || "pi";
  }

  async function start(ctx: ExtensionContext) {
    if (welSession) return;
    const res = await post("/ai/session/start", {
      tool: "pi",
      description: projectFrom(ctx),
    });
    if (typeof res?.session_id === "string") welSession = res.session_id;
  }

  // Accrue to the live Wel session; if it was swept closed during a long idle
  // gap the heartbeat is rejected (non-2xx -> null), so drop it and start fresh.
  async function heartbeat(ctx: ExtensionContext) {
    if (welSession) {
      const ok = await post("/ai/session/heartbeat", {
        session_id: welSession,
      });
      if (ok) return;
      welSession = null;
    }
    await start(ctx);
  }

  async function stop() {
    if (!welSession) return;
    const wsid = welSession;
    welSession = null;
    await post("/ai/session/stop", { session_id: wsid });
  }

  pi.on("agent_start", async (_event, ctx) => {
    await heartbeat(ctx);
  });
  pi.on("turn_end", async (_event, ctx) => {
    await heartbeat(ctx);
  });
  pi.on("tool_execution_end", async (_event, ctx) => {
    await heartbeat(ctx);
  });
  pi.on("agent_end", async (_event, ctx) => {
    await heartbeat(ctx);
  });
  pi.on("session_shutdown", async () => {
    await stop();
  });
}
